BaSP-TG-06: Create Employee component.
BaSP-a2022/alfon-a-trackgenix-app pull request #1
Opened 2022-10-29 00:44 UTC by JulianFloresDev

Development of the necessary components to implement a complete CRUD on the "Employees" entity.

> Show Resource List
> Edit Button
> Edit feature
> Delete button
> Delete feature
> Succes message
> Error message
> Redirect button to Add feature

2022-10-29 17:36 UTC, kolodani commented on src/Components/Employees/Input/index.js
> +        <span className="material-symbols-outlined icon-search" id="icon-sreach">
typo error: search not sreach

2022-11-03 17:04 UTC, kolodani approved these changes
well done, nice work!

2022-11-03 17:04 UTC, kolodani commented on src/Components/Employees/Modal/index.js
> +          {/* <button type="button" className={styles.button} onClick={() => setModalState(false)}>
why you have this code commented

2022-11-03 17:04 UTC, kolodani commented on src/Components/Employees/Table/index.js
> +                  x
i think is better use here the were 'delete' word instead of 'x'

2022-11-04 17:56 UTC, Alfondalix requested changes

2022-11-04 17:56 UTC, Alfondalix commented on src/Components/Employees/Modal/index.js
> +  console.log(modalData.message);
We should delete this line

2022-11-04 17:56 UTC, Alfondalix commented on src/Components/Employees/index.js
> +      console.log(error);
We could change it to console.error(error)

2022-11-04 17:56 UTC, Alfondalix commented on src/Components/Employees/index.js
> +// import EditEmployeeModal from './Edit';
We should delete this line if we're not using it

2022-11-04 18:06 UTC, JulianFloresDev commented on src/Components/Employees/Modal/index.js
> +          {/* <button type="button" className={styles.button} onClick={() => setModalState(false)}>
Resolve

2022-11-04 18:08 UTC, JulianFloresDev commented on src/Components/Employees/Table/index.js
> +                  x
I think I like this short way.

2022-11-04 18:13 UTC, JulianFloresDev commented on src/Components/Employees/index.js
> +      console.log(error);
Resolve

2022-11-04 18:13 UTC, JulianFloresDev commented on src/Components/Employees/index.js
> +// import EditEmployeeModal from './Edit';
Resolve

2022-11-04 18:59 UTC, FacuDLF commented on src/Components/Employees/Form/index.js
> +                // closeModal();
Commented lines should be deleted.

2022-11-04 19:17 UTC, JulianFloresDev commented on src/Components/Employees/Form/index.js
> +                // closeModal();
Changes done

2022-11-04 19:54 UTC, FacuDLF approved these changes

2022-11-05 21:21 UTC, agusgatto8 approved these changes
Done

2022-11-05 21:23 UTC, agusgatto8 approved these changes

2022-11-06 16:55 UTC, kolodani approved these changes
well done!!!

2022-11-06 22:55 UTC, Alfondalix approved these changes

2022-11-06 22:59 UTC, merged