BaSP-TG-01: super admin table
BaSP-a2022/alfon-a-trackgenix-app pull request #2
Opened 2022-10-31 04:07 UTC by kolodani

functions: show, create, edit and delete

2022-11-04 17:56 UTC, FacuDLF commented on src/Components/SuperAdmins/index.js
> +//import Modal from './Modal';
It should be erase the line commented.

2022-11-04 18:16 UTC, FacuDLF submitted a review, later dismissed

2022-11-04 19:26 UTC, FacuDLF commented on src/Components/SuperAdmins/Edit/index.js
> +      console.error(error);
Leave only the catch errors with console.error. 
console.log() should be removed

2022-11-04 19:27 UTC, FacuDLF requested changes
Using try/catch, avoid to use console.log to catch errors. Should be catched using console.error() insted.

2022-11-04 19:52 UTC, FacuDLF approved these changes

2022-11-05 18:57 UTC, anapaulib approved these changes
Done

2022-11-05 19:10 UTC, merged