BaSP-TG-47: Tasks redux structure
BaSP-a2022/alfon-a-trackgenix-app pull request #22
Opened 2022-11-15 20:33 UTC by MatiasPazConti

2022-11-15 21:21 UTC, JulianFloresDev requested changes

2022-11-15 21:21 UTC, JulianFloresDev commented on src/Components/Share/CreateForm/index.js
> +    dispatch(createTask(itemToPUT));
Remember in this case we handle this actions inside a switch structure. 

I suggest merge with any other branch to compare and handle this before you need to solve conflicts, because you will.

2022-11-15 21:21 UTC, JulianFloresDev commented on src/Components/Share/Form/index.js
> +  const { showModal, modalContent, itemToPUT } = useSelector((state) => state.global);
It's just a typo, but we decide to use **'store'** instead **'state'**

2022-11-15 23:13 UTC, JulianFloresDev submitted a review, later dismissed

2022-11-16 00:29 UTC, kolodani approved these changes
wll done !!!

2022-11-16 00:41 UTC, DinoStampella approved these changes
Well done!

2022-11-16 00:49 UTC, agusgatto8 approved these changes

2022-11-16 00:50 UTC, merged