BaSP-48: Timesheets redux structure
BaSP-a2022/alfon-a-trackgenix-app pull request #24
Opened 2022-11-16 00:18 UTC by DinoStampella

2022-11-16 00:35 UTC, MatiasPazConti requested changes
There are merging conflicts you must solve first

2022-11-16 00:35 UTC, MatiasPazConti commented on src/redux/projects/reducer.js
> +  // PUT_PROJECTS_PENDING,
Fix this comments

2022-11-16 14:09 UTC, JulianFloresDev submitted a review, later dismissed
Approved

2022-11-16 15:47 UTC, JulianFloresDev approved these changes
Approve Changes

2022-11-16 15:52 UTC, anapaulib approved these changes
Nice

2022-11-17 00:35 UTC, MatiasPazConti approved these changes

2022-11-17 00:48 UTC, merged