BaSP-TG-63: Update routes
BaSP-a2022/alfon-a-trackgenix-app pull request #30
Opened 2022-11-29 19:22 UTC by DinoStampella

2022-11-30 15:27 UTC, JulianFloresDev commented on src/Components/Auth/LogIn/index.js
> +  // sessionStorage.getItem('token') && history.push('/home');
Delete comment lines

2022-11-30 15:28 UTC, JulianFloresDev commented on src/Components/Auth/SingUp/signup.module.css
> +.sectionContainer {
Incomplete styles

2022-11-30 15:29 UTC, JulianFloresDev commented on src/Components/Share/Form/index.js
> +import { formSchema } from '../../../Validations/formSchema';
Import as relative, not as absolute route

2022-11-30 15:30 UTC, JulianFloresDev commented on src/Components/Share/Navbar/index.jsx
> +                <a href={endPoint === 'profile' ? `/${role}s/` : `/${endPoint}`}>
Add Profile endpoint correctly

2022-11-30 15:31 UTC, JulianFloresDev commented on src/Components/Share/Profile/index.jsx
> +// import { useHistory } from 'react-router-dom';
Delete comment lines

2022-11-30 15:31 UTC, JulianFloresDev commented on src/Components/Share/Profile/index.jsx
> +  // const history = useHistory();
Same as above

2022-11-30 15:31 UTC, JulianFloresDev commented on src/Components/Share/Profile/index.jsx
> +              // history.push(`/${user.token}/form/${user._id}`);
Same

2022-11-30 15:35 UTC, JulianFloresDev requested changes
Resolve comments before merge! Good job

2022-12-01 22:26 UTC, agusgatto8 approved these changes

2022-12-01 22:27 UTC, JulianFloresDev approved these changes
Approved

2022-12-01 22:28 UTC, merged