BaSP-TG-07: project table
BaSP-a2022/alfon-a-trackgenix-app pull request #5
Opened 2022-11-02 02:15 UTC by joryapur

2022-11-03 14:15 UTC, DinoStampella commented on src/Components/Projects/Button/index.js
> +      style={{ background: background }}
Maybe there is some way to avoid inline styles

2022-11-03 14:20 UTC, DinoStampella commented on src/Components/Projects/Table/table.module.css
> +    width: 100%;
width property could be above text-align property

2022-11-03 14:21 UTC, DinoStampella submitted a review, later dismissed

2022-11-03 17:16 UTC, kolodani approved these changes
nice work

2022-11-03 17:16 UTC, kolodani commented on src/Components/Projects/Button/index.js
> +      style={{ background: background }}
you can add a className to solve the problem and import the style here

2022-11-04 19:20 UTC, FacuDLF requested changes
Avoid to use console.log() for errors. Using try/catch, to catch errors correctly, should use catch.error().

2022-11-04 19:21 UTC, FacuDLF commented on src/Components/Projects/Form/index.js
> +      console.log(error);
Replace console.log() by console.error()

2022-11-04 19:21 UTC, FacuDLF commented on src/Components/Projects/Form/index.js
> +      console.log(error);
Replace console.log() by console.error()

2022-11-07 14:03 UTC, closed without merging