BaSP-TG-08: Tasks table resources
BaSP-a2022/alfon-a-trackgenix-app pull request #6
Opened 2022-11-02 12:20 UTC by DinoStampella

2022-11-03 17:11 UTC, kolodani approved these changes
great work, well done

2022-11-04 17:41 UTC, Alfondalix requested changes

2022-11-04 17:41 UTC, Alfondalix commented on src/Components/Tasks/index.js
> +    console.log(JSON.stringify(data));
We should delete this line

2022-11-04 17:41 UTC, Alfondalix commented on src/Components/Tasks/index.js
> +  // Delete Task
We could delete this comment

2022-11-04 17:41 UTC, Alfondalix commented on src/Components/Tasks/index.js
> +  // Hide edit modal
Same as above

2022-11-04 17:41 UTC, Alfondalix commented on src/Components/Tasks/index.js
> +  //Add task
Same here

2022-11-04 17:41 UTC, Alfondalix commented on src/Components/Tasks/index.js
> +      console.log(error);
We could use console.error(error) instead

2022-11-04 17:41 UTC, Alfondalix commented on src/Components/Tasks/index.js
> +      console.log(err);
Same as the other comment about console.error

2022-11-04 17:41 UTC, Alfondalix commented on src/Components/Tasks/index.js
> +      console.log(error);
SAme here

2022-11-05 21:26 UTC, LuisQueff approved these changes
Ready to merge

2022-11-06 23:05 UTC, kolodani approved these changes
nice work!!!

2022-11-06 23:06 UTC, Alfondalix approved these changes

2022-11-06 23:07 UTC, merged