BaSP-TG-19: Create Share Component Folder
BaSP-a2022/alfon-a-trackgenix-app pull request #9
Opened 2022-11-06 03:25 UTC by JulianFloresDev

- Create folder to Share components.
- Create fisrt Share component -> Table Component
- Create second Share component -> Table Header Component with filter option

2022-11-07 19:37 UTC, Alfondalix requested changes

2022-11-07 19:37 UTC, Alfondalix commented on src/Components/Layout/index.js
> +          <Route exact path={'/tasks'} component={Tasks} />
Good catch

2022-11-07 19:37 UTC, Alfondalix commented on src/Components/Share/Table/index.js
> +    console.log('Open Modal Component');
We should delete this line

2022-11-07 19:37 UTC, Alfondalix commented on src/Components/Share/Table/index.js
> +    console.log('Open Modal Component with employee List:', list);
Same as above

2022-11-07 19:37 UTC, Alfondalix commented on src/Components/Share/Table/index.js
> +                          </ul> */}
What about this commented lines? If we're not going to use them we should delete them

2022-11-07 19:43 UTC, JulianFloresDev commented on src/Components/Share/Table/index.js
> +                          </ul> */}
That was from old Wayne to send employee list from teamMmbers. After meet we decide remove this. It should be remove

2022-11-07 19:44 UTC, JulianFloresDev commented on src/Components/Share/Table/index.js
> +    console.log('Open Modal Component with employee List:', list);
It still in progress, but should be change for a real function

2022-11-07 19:45 UTC, JulianFloresDev commented on src/Components/Share/Table/index.js
> +    console.log('Open Modal Component');
Still in progress, same as 👇

2022-11-08 03:20 UTC, kolodani approved these changes
Well Done!!!

2022-11-08 03:31 UTC, DinoStampella approved these changes

2022-11-08 03:55 UTC, LuisQueff approved these changes

2022-11-08 13:51 UTC, Alfondalix approved these changes

2022-11-08 13:51 UTC, merged